Update NigeriaDecides.yml

diff --git a/.github/workflows/NigeriaDecides.yml b/.github/workflows/NigeriaDecides.yml
--- a/.github/workflows/NigeriaDecides.yml
+++ b/.github/workflows/NigeriaDecides.yml
@@ -34,18 +34,17 @@ jobs:
               
           - name: Execute pyhon script
             run: python NigeriaDecides.py
-          - name: Commit and push if it change
+          - name: Commit and push if it changes
             run: |
               git config --local user.name actions-user
               git config --local user.email "actions@github.com"
               git add -A
-              git commit -m "Latest Data" || exit 0
-              git push origin main
-            env: 
-              REPO_KEY: ${{secrets.GITHUB_TOKEN}}
+              git commit -m "Latest Data"
+              if [ $? -eq 0 ]; then
+                git push origin main
+              else
+                echo "Commit failed"; exit 1;
+              fi
+            env:
+              REPO_KEY: ${{ secrets.GITHUB_TOKEN }}
               username: github-actions
-          - name: Push changes # push the output folder to your repo, turn on workflow read and write permission
-            uses: ad-m/github-push-action@master
-            with:
-              github_token: ${{ secrets.GITHUB_TOKEN }}
-              force: true
